In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups.csv")

In [3]:
dataset

    RandD Spend  Administration  Marketing Spend       State     Profit
0     165349.20       136897.80        471784.10    New York  192261.83
1     162597.70       151377.59        443898.53  California  191792.06
2     153441.51       101145.55        407934.54     Florida  191050.39
3     144372.41       118671.85        383199.62    New York  182901.99
4     142107.34        91391.77        366168.42     Florida  166187.94
5     131876.90        99814.71        362861.36    New York  156994.12
6     134615.46       147198.87        127716.82  California  156122.51
7     130298.13       145530.06        323876.68     Florida  155752.60
8     120542.52       148718.85        311613.28    New York  152211.77
9      94657.16       145077.58        282574.31    New York  125370.37
10     91749.16       114175.79        294919.57     Florida  124266.90
11     86419.70       153514.11             0.00    New York  122776.86
12     76253.86       113867.30        298664.47  California  118474.03
13     78389.47       153773.43        299737.29    New York  111313.02
14     73994.56       122782.75        303319.26     Florida  110352.25
15     67532.53       105751.03        304768.73     Florida  108733.99
16     94657.16       145077.58        282574.31    New York  125370.37
17     91749.16       114175.79        294919.57     Florida  124266.90
18     86419.70       153514.11             0.00    New York  122776.86
19     76253.86       113867.30        298664.47  California  118474.03
20     78389.47       153773.43        299737.29    New York  111313.02
21     73994.56       122782.75        303319.26     Florida  110352.25
22     67532.53       105751.03        304768.73     Florida  108733.99
23     77044.01        99281.34        140574.81    New York  108552.04
24     64664.71       139553.16        137962.62  California  107404.34
25     75328.87       144135.98        134050.07     Florida  105733.54

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,RandD Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156994.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.85,311613.28,152211.77,0,1
9,94657.16,145077.58,282574.31,125370.37,0,1
10,91749.16,114175.79,294919.57,124266.90,1,0
11,86419.70,153514.11,0.00,122776.86,0,1
12,76253.86,113867.30,298664.47,118474.03,0,0
13,78389.47,153773.43,299737.29,111313.02,0,1
14,73994.56,122782.75,303319.26,110352.25,1,0
15,67532.53,105751.03,304768.73,108733.99,1,0
16,94657.16,145077.58,282574.31,125370.37,0,1
17,91749.16,114175.79,294919.57,124266.90,1,0
18,86419.70,153514.11,0.00,122776.86,0,1
19,76253.86,113867.30,298664.47,118474.03,0,0
20,78389.47,153773.43,299737.29,111313.02,0,1
21,73994.56,122782.75,303319.26,110352.25,1,0
22,67532.53,105751.03,304768.73,108733.99,1,0
23,77044.01,99281.34,140574.81,108552.04,0,1
24,64664.71,139553.16,137962.62,107404.34,0,0
25,75328.87,144135.98,134050.07,105733.54,1,0

In [6]:
dataset.columns

Index(['RandD Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
Independent=dataset[['RandD Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [8]:
Independent

,RandD Spend,Administration,Marketing Spend,State_Florida,State_New York
0,165349.20,136897.80,471784.10,0,1
1,162597.70,151377.59,443898.53,0,0
2,153441.51,101145.55,407934.54,1,0
3,144372.41,118671.85,383199.62,0,1
4,142107.34,91391.77,366168.42,1,0
5,131876.90,99814.71,362861.36,0,1
6,134615.46,147198.87,127716.82,0,0
7,130298.13,145530.06,323876.68,1,0
8,120542.52,148718.85,311613.28,0,1
9,94657.16,145077.58,282574.31,0,1
10,91749.16,114175.79,294919.57,1,0
11,86419.70,153514.11,0.00,0,1
12,76253.86,113867.30,298664.47,0,0
13,78389.47,153773.43,299737.29,0,1
14,73994.56,122782.75,303319.26,1,0
15,67532.53,105751.03,304768.73,1,0
16,94657.16,145077.58,282574.31,0,1
17,91749.16,114175.79,294919.57,1,0
18,86419.70,153514.11,0.00,0,1
19,76253.86,113867.30,298664.47,0,0
20,78389.47,153773.43,299737.29,0,1
21,73994.56,122782.75,303319.26,1,0
22,67532.53,105751.03,304768.73,1,0
23,77044.01,99281.34,140574.81,0,1
24,64664.71,139553.16,137962.62,0,0
25,75328.87,144135.98,134050.07,1,0

In [9]:
dependent=dataset[["Profit"]]

In [10]:
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156994.12
6   156122.51
7   155752.60
8   152211.77
9   125370.37
10  124266.90
11  122776.86
12  118474.03
13  111313.02
14  110352.25
15  108733.99
16  125370.37
17  124266.90
18  122776.86
19  118474.03
20  111313.02
21  110352.25
22  108733.99
23  108552.04
24  107404.34
25  105733.54

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(Independent,dependent,test_size=0.30,random_state=0)

In [12]:
x_train

,RandD Spend,Administration,Marketing Spend,State_Florida,State_New York
18,86419.70,153514.11,0.00,0,1
19,76253.86,113867.30,298664.47,0,0
16,94657.16,145077.58,282574.31,0,1
1,162597.70,151377.59,443898.53,0,0
10,91749.16,114175.79,294919.57,1,0
25,75328.87,144135.98,134050.07,1,0
24,64664.71,139553.16,137962.62,0,0
8,120542.52,148718.85,311613.28,0,1
6,134615.46,147198.87,127716.82,0,0
4,142107.34,91391.77,366168.42,1,0
9,94657.16,145077.58,282574.31,0,1
7,130298.13,145530.06,323876.68,1,0
23,77044.01,99281.34,140574.81,0,1
3,144372.41,118671.85,383199.62,0,1
0,165349.20,136897.80,471784.10,0,1
21,73994.56,122782.75,303319.26,1,0
15,67532.53,105751.03,304768.73,1,0
12,76253.86,113867.30,298664.47,0,0

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
x_train

array([[-0.54250646,  1.23113842, -2.32102105, -0.70710678,  1.25356634],
       [-0.84995648, -0.8294321 ,  0.22216647, -0.70710678, -0.79772404],
       [-0.2933773 ,  0.79266518,  0.08515555, -0.70710678,  1.25356634],
       [ 1.76137862,  1.12009669,  1.45886345, -0.70710678, -0.79772404],
       [-0.38132524, -0.8133989 ,  0.1902779 ,  1.41421356, -0.79772404],
       [-0.87793136,  0.74372724, -1.17955797,  1.41421356, -0.79772404],
       [-1.20045229,  0.50554355, -1.14624183, -0.70710678, -0.79772404],
       [ 0.48948514,  0.98191354,  0.33242817, -0.70710678,  1.25356634],
       [ 0.91509931,  0.90291535, -1.23348686, -0.70710678, -0.79772404],
       [ 1.14167956, -1.99755671,  0.79697606,  1.41421356, -0.79772404],
       [-0.2933773 ,  0.79266518,  0.08515555, -0.70710678,  1.25356634],
       [ 0.78452838,  0.816182  ,  0.43685346,  1.41421356, -0.79772404],
       [-0.82605962, -1.58751073, -1.12399851, -0.70710678,  1.25356634],
       [ 1.21018308, -0.57972439,  0.94200013, -0.70710678,  1.25356634],
       [ 1.84459346,  0.36753606,  1.69631464, -0.70710678,  1.25356634],
       [-0.91828549, -0.36606788,  0.26180293,  1.41421356, -0.79772404],
       [-1.11371953, -1.25126041,  0.27414546,  1.41421356, -0.79772404],
       [-0.84995648, -0.8294321 ,  0.22216647, -0.70710678, -0.79772404]])

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'C':[10,100,1000,2000,3000],'gamma':['auto','scale'],'kernel':['rbf','poly','sigmoid','linear']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [16]:
re=grid.cv_results_
print("R_score value for the best parameter {}:".format(grid.best_params_))

R_score value for the best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}:

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.049346,0.030030,0.006190,0.002055,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.238521,-0.024391,-3.902851,-0.972827,-9.077630,-2.843244,3.412310,31
1,0.085032,0.035524,0.005994,0.000386,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-0.237614,-0.023771,-3.913872,-0.972002,-9.087058,-2.846864,3.416773,32
2,0.099034,0.043814,0.006303,0.001014,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.236768,-0.022663,-3.900565,-0.969988,-9.066027,-2.839202,3.408793,26
3,0.021633,0.001625,0.009887,0.003545,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.225296,-0.010528,-3.889120,-0.948295,-8.951706,-2.804989,3.372495,21
4,0.035177,0.013496,0.012379,0.007976,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.238538,-0.024366,-3.902851,-0.972876,-9.077562,-2.843238,3.412282,30
5,0.043400,0.016493,0.023950,0.010372,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.237452,-0.023973,-3.913851,-0.971413,-9.087653,-2.846868,3.417045,33
6,0.020711,0.005606,0.010234,0.002855,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.236708,-0.022760,-3.900569,-0.969742,-9.066904,-2.839337,3.409134,27
7,0.019793,0.001973,0.008671,0.001441,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.225296,-0.010528,-3.889120,-0.948295,-8.951706,-2.804989,3.372495,21
8,0.018396,0.002057,0.006692,0.001098,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.232735,-0.016861,-3.884836,-0.956959,-8.943497,-2.806978,3.366086,24
9,0.015035,0.002508,0.007902,0.001749,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",-0.223698,-0.010680,-3.995420,-0.948750,-9.037237,-2.843157,3.410795,28
10,0.015102,0.001103,0.006761,0.000786,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.215316,0.000266,-3.862210,-0.928773,-8.828551,-2.766917,3.331360,19
11,0.017900,0.003979,0.007335,0.000581,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",-0.115751,0.116003,-3.754792,-0.760105,-7.731307,-2.449190,2.982734,12
12,0.022749,0.003222,0.007099,0.000350,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.232903,-0.016605,-3.884837,-0.957447,-8.942825,-2.806923,3.365805,23
13,0.029218,0.007984,0.006139,0.002013,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.222090,-0.012692,-3.995205,-0.942896,-9.043167,-2.843210,3.413498,29
14,0.027612,0.009294,0.005971,0.001298,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.214719,-0.000686,-3.862248,-0.926342,-8.837206,-2.768240,3.334715,20
15,0.050821,0.018186,0.007102,0.000219,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",-0.115751,0.116003,-3.754792,-0.760105,-7.731307,-2.449190,2.982734,12
16,0.026663,0.012369,0.007035,0.000624,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.181028,0.055586,-3.712377,-0.908791,-7.665990,-2.482520,2.918780,16
17,0.044926,0.015711,0.004428,0.002103,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",-0.092050,0.103162,-4.498992,-0.716783,-9.292651,-2.899463,3.608123,34
18,0.039109,0.028138,0.006751,0.000511,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.036637,0.211550,-3.535453,-0.660335,-7.299919,-2.264159,2.850905,10
19,0.050235,0.029039,0.005605,0.001681,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.707799,0.686418,-1.575934,0.087377,-15.317046,-3.082277,6.173704,35
20,0.039442,0.020482,0.005998,0.002060,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.182479,0.058073,-3.712381,-0.915767,-7.659552,-2.482421,2.915947,15
21,0.077291,0.009556,0.005184,0.001690,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-0.077955,0.086645,-4.499273,-0.671786,-8.872940,-2.807062,3.465239,25
22,0.094601,0.042912,0.006947,0.000704,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.031904,0.203424,-3.535517,-0.648924,-7.269129,-2.256410,2.840658,9
23,0.063801,0.023372,0.005650,0.001825,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.707799,0.686418,-1.575934,0.087377,-15.317046,-3.082277,6.173704,35
24,0.118260,0.071835,0.005141,0.001514,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.126293,0.129987,-3.530557,-0.883634,-6.651132,-2.212326,2.570763,8
25,0.099598,0.042697,0.006191,0.000469,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.037023,0.216949,-4.382222,-0.524295,-13.715972,-3.673703,5.294801,38
26,0.117602,0.054635,0.004832,0.001403,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.144749,0.301989,-3.218284,-0.511966,-9.001254,-2.456953,3.509162,14
27,0.112888,0.051149,0.005844,0.000480,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.946198,0.895240,-0.164800,0.808317,0.280086,0.553008,0.430497,3
28,0.087361,0.056637,0.005592,0.000372,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.129092,0.134805,-3.530503,-0.894082,-6.625895,-2.208954,2.561397,7
29,0.131195,0.003179,0.004725,0.000217,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.062314,0.186287,-4.382761,-0.441195,-12.689060,-3.452883,4.916138,37
30,0.108707,0.049084,0.005037,0.000147,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.153147,0.296414,-3.219127,-0.507704,-8.932645,-2.441983,3.484468,11
31,0.148180,0.006154,0.004941,0.001412,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.946198,0.895240,-0.164800,0.808317,0.280086,0.553008,0.430497,3
32,0.170607,0.052024,0.004434,0.001254,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.073090,0.194794,-3.485532,-0.822170,-6.189886,-2.075177,2.435203,6
33,0.115112,0.050039,0.004969,0.000544,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.152904,0.321552,-4.270472,-0.345403,-19.062616,-4.640807,7.405146,40
34,0.142382,0.001493,0.004837,0.000502,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.315037,0.423149,-2.688709,-0.432462,-10.896659,-2.655929,4.269938,18
35,0.153355,0.004742,0.004807,0.001427,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.932453,0.975986,0.451983,0.941307,0.678444,0.796035,0.202136,1
36,0.181223,0.052877,0.004542,0.000146,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.077189,0.201967,-3.485374,-0.833714,-6.156370,-2.070136,2.423355,5
37,0.120429,0.055957,0.004355,0.001467,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.186493,0.279118,-4.271245,-0.231098,-17.241015,-4.255549,6.709899,39
38,0.157606,0.047083,0.005077,0.000165,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.329345,0.412515,-2.689828,-0.415445,-10.783203,-2.629323,4.228408,17
39,0.109406,0.046938,0.005087,0.000657,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.932453,0.975986,0.451983,0.941307,0.678444,0.796035,0.202136,1

In [19]:
RandD_Spend_input = float(input("R&D_Spend: "))
Administration_input = float(input("Administration: "))
Marketing_Spend_input = float(input("Marketing_Spend: "))
State_Florida_input=int(input("State_Florida 0 or 1:"))
State_New_York_input=int(input("State_New York yes 0 or 1:"))

R&D_Spend:  5233
Administration:  4532
Marketing_Spend:  524
State_Florida 0 or 1: 1
State_New York yes 0 or 1: 0

In [20]:
Future_Prediction=grid.predict([[RandD_Spend_input,Administration_input,Marketing_Spend_input,State_Florida_input,State_New_York_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1.34361161e+08]