In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
dataset=pd.read_csv("Construction_Cost_Prediction_Sample.csv")

In [23]:
dataset

,Project_ID,Area_sqft,Floors,Foundation_Type,Structure_Type,Steel_kg,Cement_Bags,Sand_cft,Labour_Days,Location_Factor,Project_Duration_Days,Total_Cost_INR
0,1,1200,1,Isolated,RCC,4200,380,1800,95,1.0,120,2400000
1,2,1800,2,Raft,RCC,7600,620,2900,160,1.1,180,4650000
2,3,2500,2,Pile,PEB,6800,540,2600,145,1.2,150,5200000
3,4,3200,3,Raft,RCC,11800,920,4200,240,1.3,240,8600000
4,5,1500,1,Isolated,Load Bearing,3500,310,1500,80,0.9,100,2100000
5,6,2200,2,Raft,RCC,8900,700,3300,175,1.2,190,5900000
6,7,4000,4,Pile,RCC,15500,1250,5600,330,1.4,320,12800000
7,8,2800,2,Pile,PEB,7900,610,3000,150,1.1,170,6100000
8,9,3500,3,Raft,RCC,13200,980,4700,275,1.3,260,9800000
9,10,1000,1,Isolated,Load Bearing,2600,240,1200,60,0.8,90,1600000

In [24]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [25]:
dataset

,Project_ID,Area_sqft,Floors,Steel_kg,Cement_Bags,Sand_cft,Labour_Days,Location_Factor,Project_Duration_Days,Total_Cost_INR,Foundation_Type_Pile,Foundation_Type_Raft,Structure_Type_PEB,Structure_Type_RCC
0,1,1200,1,4200,380,1800,95,1.0,120,2400000,0,0,0,1
1,2,1800,2,7600,620,2900,160,1.1,180,4650000,0,1,0,1
2,3,2500,2,6800,540,2600,145,1.2,150,5200000,1,0,1,0
3,4,3200,3,11800,920,4200,240,1.3,240,8600000,0,1,0,1
4,5,1500,1,3500,310,1500,80,0.9,100,2100000,0,0,0,0
5,6,2200,2,8900,700,3300,175,1.2,190,5900000,0,1,0,1
6,7,4000,4,15500,1250,5600,330,1.4,320,12800000,1,0,0,1
7,8,2800,2,7900,610,3000,150,1.1,170,6100000,1,0,1,0
8,9,3500,3,13200,980,4700,275,1.3,260,9800000,0,1,0,1
9,10,1000,1,2600,240,1200,60,0.8,90,1600000,0,0,0,0

In [26]:
dataset.columns

Index(['Project_ID', 'Area_sqft', 'Floors', 'Steel_kg', 'Cement_Bags',
       'Sand_cft', 'Labour_Days', 'Location_Factor', 'Project_Duration_Days',
       'Total_Cost_INR', 'Foundation_Type_Pile', 'Foundation_Type_Raft',
       'Structure_Type_PEB', 'Structure_Type_RCC'],
      dtype='object')

In [27]:
Independent=dataset[['Project_ID', 'Area_sqft', 'Floors', 'Steel_kg', 'Cement_Bags',
       'Sand_cft', 'Labour_Days', 'Location_Factor', 'Project_Duration_Days',
        'Foundation_Type_Pile', 'Foundation_Type_Raft',
       'Structure_Type_PEB', 'Structure_Type_RCC']]

In [28]:
Independent

,Project_ID,Area_sqft,Floors,Steel_kg,Cement_Bags,Sand_cft,Labour_Days,Location_Factor,Project_Duration_Days,Foundation_Type_Pile,Foundation_Type_Raft,Structure_Type_PEB,Structure_Type_RCC
0,1,1200,1,4200,380,1800,95,1.0,120,0,0,0,1
1,2,1800,2,7600,620,2900,160,1.1,180,0,1,0,1
2,3,2500,2,6800,540,2600,145,1.2,150,1,0,1,0
3,4,3200,3,11800,920,4200,240,1.3,240,0,1,0,1
4,5,1500,1,3500,310,1500,80,0.9,100,0,0,0,0
5,6,2200,2,8900,700,3300,175,1.2,190,0,1,0,1
6,7,4000,4,15500,1250,5600,330,1.4,320,1,0,0,1
7,8,2800,2,7900,610,3000,150,1.1,170,1,0,1,0
8,9,3500,3,13200,980,4700,275,1.3,260,0,1,0,1
9,10,1000,1,2600,240,1200,60,0.8,90,0,0,0,0

In [29]:
dependent=dataset[['Total_Cost_INR']]

In [30]:
dependent

   Total_Cost_INR
0         2400000
1         4650000
2         5200000
3         8600000
4         2100000
5         5900000
6        12800000
7         6100000
8         9800000
9         1600000

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'C':[100,200],'gamma':['auto','scale'],'kernel':['rbf']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(Independent,dependent)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [100, 200], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf']},
             verbose=3)

In [32]:
re=grid.cv_results_
print("R_score value for the best parameter {}:".format(grid.best_params_))

R_score value for the best parameter {'C': 200, 'gamma': 'scale', 'kernel': 'rbf'}:

In [33]:
table=pd.DataFrame.from_dict(re)

In [34]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024411,0.005659,0.009096,0.002398,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-4.840000,-0.913711,-0.754155,-1.824515,-0.001338,-1.666744,1.689254,3
1,0.017787,0.007210,0.006425,0.001868,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-4.839525,-0.913525,-0.754026,-1.824371,-0.001257,-1.666541,1.689120,2
2,0.022253,0.005665,0.008586,0.001852,200,auto,rbf,"{'C': 200, 'gamma': 'auto', 'kernel': 'rbf'}",-4.840000,-0.913711,-0.754155,-1.824515,-0.001338,-1.666744,1.689254,3
3,0.017623,0.005135,0.007106,0.002428,200,scale,rbf,"{'C': 200, 'gamma': 'scale', 'kernel': 'rbf'}",-4.839051,-0.913339,-0.753897,-1.824226,-0.001175,-1.666337,1.688985,1

In [35]:
Project_ID_input= float(input("Project_ID"))
Area_sqft_input = float(input("Area_sqft"))
Floors_input= float(input("Floors"))
Steel_kg_input=int(input("Steel_kg"))
Cement_Bags_input=int(input("Cement_Bags"))   
Sand_cft_input= float(input("Sand_cft")) 
Labour_Days_input= float(input("Labour_Days")) 
Location_Factor_input= float(input("Location_Factor")) 
Project_Duration_Days_input= float(input("Project_Duration_Days")) 
Foundation_Type_Pile_input= float(input("Foundation_Type_Pile"))  
Foundation_Type_Raft_input= float(input("Foundation_Type_Raft")) 
Structure_Type_PEB_input= float(input("Structure_Type_PEB"))  
Structure_Type_RCC_input= float(input("Structure_Type_RCC"))

Project_ID 3
Area_sqft 3200
Floors 3
Steel_kg 15000
Cement_Bags 400
Sand_cft 1600
Labour_Days 350
Location_Factor 1.5
Project_Duration_Days 400
Foundation_Type_Pile 0
Foundation_Type_Raft 0
Structure_Type_PEB 0
Structure_Type_RCC 0

In [36]:
Future_Prediction=grid.predict([[Project_ID_input,Area_sqft_input,Floors_input,Steel_kg_input,Cement_Bags_input,Sand_cft_input,Labour_Days_input,Location_Factor_input,Project_Duration_Days_input,Foundation_Type_Pile_input,Foundation_Type_Raft_input,Structure_Type_PEB_input,Structure_Type_RCC_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5550485.1938505]

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(