In [1]:
import pandas as pd

In [2]:
dataset= pd.read_csv("50_Startups.csv")

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156994.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.85        311613.28    New York  152211.77
9    94657.16       145077.58        282574.31    New York  125370.37
10   91749.16       114175.79        294919.57     Florida  124266.90
11   86419.70       153514.11             0.00    New York  122776.86
12   76253.86       113867.30        298664.47  California  118474.03
13   78389.47       153773.43        299737.29    New York  111313.02
14   73994.56       122782.75        303319.26     Florida  110352.25
15   67532.53       105751.03        304768.73     Florida  108733.99
16   94657.16       145077.58        282574.31    New York  125370.37
17   91749.16       114175.79        294919.57     Florida  124266.90
18   86419.70       153514.11             0.00    New York  122776.86
19   76253.86       113867.30        298664.47  California  118474.03
20   78389.47       153773.43        299737.29    New York  111313.02
21   73994.56       122782.75        303319.26     Florida  110352.25
22   67532.53       105751.03        304768.73     Florida  108733.99
23   77044.01        99281.34        140574.81    New York  108552.04
24   64664.71       139553.16        137962.62  California  107404.34
25   75328.87       144135.98        134050.07     Florida  105733.54

In [4]:
dataset=pd.get_dummies(dataset,dtype=int ,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156994.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.85,311613.28,152211.77,0,1
9,94657.16,145077.58,282574.31,125370.37,0,1
10,91749.16,114175.79,294919.57,124266.90,1,0
11,86419.70,153514.11,0.00,122776.86,0,1
12,76253.86,113867.30,298664.47,118474.03,0,0
13,78389.47,153773.43,299737.29,111313.02,0,1
14,73994.56,122782.75,303319.26,110352.25,1,0
15,67532.53,105751.03,304768.73,108733.99,1,0
16,94657.16,145077.58,282574.31,125370.37,0,1
17,91749.16,114175.79,294919.57,124266.90,1,0
18,86419.70,153514.11,0.00,122776.86,0,1
19,76253.86,113867.30,298664.47,118474.03,0,0
20,78389.47,153773.43,299737.29,111313.02,0,1
21,73994.56,122782.75,303319.26,110352.25,1,0
22,67532.53,105751.03,304768.73,108733.99,1,0
23,77044.01,99281.34,140574.81,108552.04,0,1
24,64664.71,139553.16,137962.62,107404.34,0,0
25,75328.87,144135.98,134050.07,105733.54,1,0

In [5]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156994.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.85,311613.28,152211.77,0,1
9,94657.16,145077.58,282574.31,125370.37,0,1
10,91749.16,114175.79,294919.57,124266.90,1,0
11,86419.70,153514.11,0.00,122776.86,0,1
12,76253.86,113867.30,298664.47,118474.03,0,0
13,78389.47,153773.43,299737.29,111313.02,0,1
14,73994.56,122782.75,303319.26,110352.25,1,0
15,67532.53,105751.03,304768.73,108733.99,1,0
16,94657.16,145077.58,282574.31,125370.37,0,1
17,91749.16,114175.79,294919.57,124266.90,1,0
18,86419.70,153514.11,0.00,122776.86,0,1
19,76253.86,113867.30,298664.47,118474.03,0,0
20,78389.47,153773.43,299737.29,111313.02,0,1
21,73994.56,122782.75,303319.26,110352.25,1,0
22,67532.53,105751.03,304768.73,108733.99,1,0
23,77044.01,99281.34,140574.81,108552.04,0,1
24,64664.71,139553.16,137962.62,107404.34,0,0
25,75328.87,144135.98,134050.07,105733.54,1,0

In [6]:
Independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [7]:
dependent=dataset[["Profit"]]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(Independent,dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(Independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [12]:
weight=regressor.coef_
weight

array([[ 8.16029499e-01, -2.66251940e-02,  2.48098075e-02,
        -6.00909531e+03, -1.67381282e+03]])

In [13]:
bias=regressor.intercept_
bias

array([51563.56193681])

In [14]:
y_pred=regressor.predict(X_test)

In [15]:
from sklearn.metrics import r2_score

In [16]:
r_score=r2_score(y_test,y_pred)

In [17]:
r_score

0.944950082092763

In [25]:
import pickle 
filename="Finalized_model_mul_linear.sav"
pickle.dump(regressor,open(filename,'wb'))

In [27]:
loaded_model=pickle.load(open("Finalized_model_mul_linear.sav",'rb'))
result=loaded_model.predict([[1453,4535,485,0,1]])

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
result

array([[50966.72747948]])